---
namespace: witine
name: netbox
version: 1.0.0
readme: README.md
authors:
  - Andrew Ying <andrew@witine.com>
description: Netbox Ansible collection
license:
  - BSD-3-Clause
tags:
  - netbox
dependencies:
  community.general: '>=7.5.1'
repository: https://github.com/witine/ansible-collection-netbox
documentation: https://github.com/witine/ansible-collection-netbox
homepage: https://github.com/witine/ansible-collection-netbox
issues: https://github.com/witine/ansible-collection-netbox/issues
build_ignore:
  - .github
  - .gitignore
